### ISSUE TITLE
@inbucket is displayed instead of actual domain

### ISSUE THREAD

**Issue by tommywo** [jhillyerd/inbucket#31]
Hi! Nice app!

**Comment by jhillyerd** [comment]
Thanks!  The @inbucket (next the View button is what I'm assuming you are referring to) is intentional.  Inbucket actually accepts mail for *any* domain, so I didn't want people to think they had to send mail to just the configured smtp greeting domain.

The idea is that if you were testing your application with production data, inbucket would happily accept mail for an @gmail.com user or a @hotmail.com user.

Perhaps I should edit the default homepage (greeting.html) to make all this more clear.

**Comment by tommywo** [comment]
Ok I get it :), but the ui suggest that is for one domain only
- there is @inbucket right by search box,
- you cant search for 'user@gmail.com'
- mailbox is identified only by username, but not domain,
 so mail to user@gmail.com and user@yahoo.com will go to one mailbox 'user'

So i think it would be better to identify mailbox by complete email, and get rid of '@inbucket'  by the 'View' button.

**Comment by jhillyerd** [comment]
Definitely gonna need more docs on it.  :)  Inbucket completely ignores the domain - james@gmail.com and james@inbucket.com are both "james" as far Inbucket is concerned, and the mail goes into the same mailbox.

The reason I added the @inbucket UI element was people were confused what to type into the box at all, they thought it was a search feature.

**Comment by tommywo** [comment]
@jhillyerd we went a little off topic, making this '@inbucket' element configurable would be great. :)
