### ISSUE TITLE
Feature - Add the possibility to get the latest message 

### ISSUE THREAD

**Issue by cpanato** [jhillyerd/inbucket#50]
We use inbucket and sometimes I would like to get the latest message.

What do you think to add a new endpoint to get the latest message?
I think I can do that if you agree.

I have a question: 
```
for _, m := range mb.messages {
	if m.Fid == id {
		return m, nil
	}
}
```

Is the array order? if I get the last item will be the latest message?

thanks!

**Comment by jhillyerd** [comment]
I'm not positive where that code came from, but it should be ordered.  The "index" is in received order, and that is returned to callers here:

https://github.com/jhillyerd/inbucket/blob/master/smtpd/filestore.go#L162

It would be cool if we supported a "latest" in the {id} position, instead of adding a whole new endpoint.

Also make sure to read the contributing guidelines so you branch and file PRs to the right place.  Thanks!
